workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods and pods
        script: |
          sudo gem install cocoapods
          pod setup
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --no-codesign
