workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Patch Podfile for CocoaPods 1.16
        script: |
          sed -i '' '/post_install do |installer|/,$d' ios/Podfile
          cat <<'EOF' >> ios/Podfile

          post_install do |installer|
            installer.aggregate_targets.each do |target|
              if target.platform.name == :ios
                flutter_additional_ios_build_settings(installer)
              end
            end
          end
          EOF
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --debug --no-codesign

