workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Pod setup
        script: |
          cd ios
          pod deintegrate
          pod repo update --verbose
          pod install --verbose
          cd ..
      - name: Build iOS (verbose)
        script: |
          set -o pipefail
          flutter build ios --release --no-codesign --verbose 2>&1 | tee build_log.txt
    artifacts:
      - build_log.txt
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

