// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOu4-dOKxM3uCYF57fZwzWfdfwkBIfp9k',
    appId: '1:810542727857:web:4e1d87c8222b8c47829890',
    messagingSenderId: '810542727857',
    projectId: 'citysync-2025',
    authDomain: 'citysync-2025.firebaseapp.com',
    storageBucket: 'citysync-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnPxlcCY0FJMCEsW1SjNdNFe5RjwRcJWY',
    appId: '1:810542727857:android:ca5b8979616859d7829890',
    messagingSenderId: '810542727857',
    projectId: 'citysync-2025',
    storageBucket: 'citysync-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oUHKp8oBmf4bwjfr3lPRnue5xIyXglw',
    appId: '1:810542727857:ios:70a0b2828d6d35d2829890',
    messagingSenderId: '810542727857',
    projectId: 'citysync-2025',
    storageBucket: 'citysync-2025.firebasestorage.app',
    iosBundleId: 'com.example.myfirstflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oUHKp8oBmf4bwjfr3lPRnue5xIyXglw',
    appId: '1:810542727857:ios:70a0b2828d6d35d2829890',
    messagingSenderId: '810542727857',
    projectId: 'citysync-2025',
    storageBucket: 'citysync-2025.firebasestorage.app',
    iosBundleId: 'com.example.myfirstflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOu4-dOKxM3uCYF57fZwzWfdfwkBIfp9k',
    appId: '1:810542727857:web:028c6d8d95aac7e6829890',
    messagingSenderId: '810542727857',
    projectId: 'citysync-2025',
    authDomain: 'citysync-2025.firebaseapp.com',
    storageBucket: 'citysync-2025.firebasestorage.app',
  );
}
