// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByTjB_XxTvyUkE6n0L3PpNrUQA8nJZmdk',
    appId: '1:900337768002:web:b30a47fae86950cd52bfdb',
    messagingSenderId: '900337768002',
    projectId: 'next-discovery-5e820',
    authDomain: 'next-discovery-5e820.firebaseapp.com',
    storageBucket: 'next-discovery-5e820.firebasestorage.app',
    measurementId: 'G-ZDSCJ1CBRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTjB_XxTvyUkE6n0L3PpNrUQA8nJZmdk',
    appId: '1:900337768002:android:PLACEHOLDER',
    messagingSenderId: '900337768002',
    projectId: 'next-discovery-5e820',
    storageBucket: 'next-discovery-5e820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByTjB_XxTvyUkE6n0L3PpNrUQA8nJZmdk',
    appId: '1:900337768002:ios:PLACEHOLDER',
    messagingSenderId: '900337768002',
    projectId: 'next-discovery-5e820',
    storageBucket: 'next-discovery-5e820.firebasestorage.app',
    iosBundleId: 'com.example.nextdiscovery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByTjB_XxTvyUkE6n0L3PpNrUQA8nJZmdk',
    appId: '1:900337768002:ios:PLACEHOLDER',
    messagingSenderId: '900337768002',
    projectId: 'next-discovery-5e820',
    storageBucket: 'next-discovery-5e820.firebasestorage.app',
    iosBundleId: 'com.example.nextdiscovery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByTjB_XxTvyUkE6n0L3PpNrUQA8nJZmdk',
    appId: '1:900337768002:web:b30a47fae86950cd52bfdb',
    messagingSenderId: '900337768002',
    projectId: 'next-discovery-5e820',
    authDomain: 'next-discovery-5e820.firebaseapp.com',
    storageBucket: 'next-discovery-5e820.firebasestorage.app',
    measurementId: 'G-ZDSCJ1CBRS',
  );
}