# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

use_frameworks! :linkage => :static
use_modular_headers!

target 'Runner' do
  flutter_application_path = '../'
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))
end
