# Uncomment the next line to define a global platform for your project
platform :ios, '15.0' # or '16.0', '17.0' depending on your app's requirements:cite[1]:cite[8]
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# ... (rest of your Podfile, like the flutter_root definition) ...

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
